/** 固定安装原生循环的授权、目标新鲜度、显式反馈与输出谱系探针。 */
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync,cpSync,chmodSync,lstatSync,existsSync} from 'node:fs';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
const hash=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
const c=JSON.parse(readFileSync(process.argv[2],'utf8'));mkdirSync(c.output,{recursive:true});const originalSource=c.source;cpSync(c.source,join(c.output,'source'),{recursive:true});c.source=join(c.output,'source');
const load=async(p:string)=>import(pathToFileURL(join(c.installed,p)).href);
const {skillDigest}=await load('src/harness/controller.ts'),{ReviewStore}=await load('src/evaluation/review_store.ts'),{RevisionCycle}=await load('src/evaluation/revision_cycle.ts'),{TechnicalReview}=await load('src/evaluation/technical_review.ts');
const lock=JSON.parse(readFileSync(join(c.installed,'skills.lock.json'),'utf8')).sources[0],originalDigest=skillDigest(originalSource),sourceManifest=JSON.parse(readFileSync(join(c.source,'manifest.json'),'utf8'));
const brief=join(c.output,'brief.txt'),rubric=join(c.output,'rubric.json');writeFileSync(brief,'Explicit QA green target');writeFileSync(rubric,'{}');
const field='appearance.items.0.paint',value={type:'solid',color:{model:'rgb',r:0,g:1,b:0}},changes=[{objectId:2,field,value}],roots=[c.output,c.runtime];
const authorization={objects:[2,3],fields:[field,'kind.runs.0.text'],deadline:Date.now()+180000,maxAttempts:30,maxBytes:128*1024*1024,budgetId:'revision-guards',readRoots:roots,writeRoots:roots};
const store=new ReviewStore(join(c.output,'state.sqlite'),roots),cycle=new RevisionCycle(store);const records:any[]=[];
const attempts=()=>Number((store.db.prepare('SELECT attempts FROM budgets WHERE id=?').get(authorization.budgetId) as any).attempts);
const receipt=(r:any,scores:any,message:string)=>({schema:'vectorcraft-review-receipt/v1',requestId:r.id,bindingHash:r.bindingHash,reviewer:{kind:'human',identity:'explicit QA feedback; not actual creative review',contextOrigin:'same native acceptance driver',independenceEvidence:null},verdict:'revise',issues:[{objectId:2,field,message,evidence:['artboard-1.png']}],scores});
const check=async(directory:string)=>{const m=JSON.parse(readFileSync(join(directory,'manifest.json'),'utf8'));return new TechnicalReview(store).request({native:join(directory,'project.vectorcraft'),projectRevision:m.files['project.vectorcraft'],runtimeIdentity:m.runtimeSha256,candidates:m.outputs.map((x:any)=>join(directory,x.path)),targets:[{path:brief,role:'target'}],rubric,exchangeLoss:join(directory,'exchange-loss.json'),technicalStatus:'PASS',authorization},{python:'/opt/anaconda3/bin/python3'});};
function refusal(name:string,fn:()=>any,pattern:RegExp){const before=attempts();let error='';try{fn();}catch(e){error=String(e);}assert.match(error,pattern);assert.equal(attempts(),before);records.push({case:name,result:'PASS',error,attemptsBefore:before,attemptsAfter:attempts()});}
async function refusedExecution(name:string,proposal:any,options:any,pattern:RegExp){const before=attempts();let error='';try{await cycle.execute('guards',proposal.id,options);}catch(e){error=String(e);}assert.match(error,pattern);assert.equal(attempts(),before);assert.equal(existsSync(options.output),false);records.push({case:name,result:'PASS',error,attemptsBefore:before,attemptsAfter:attempts(),outputAbsent:true});}
try{
 const first=await check(c.source);assert.equal(first.input.technicalStatus,'PASS');store.importReceipt(receipt(first,{structure:2,text:2,brand:2,layout:2,legibility:2},'QA initial paint issue'));cycle.open({id:'guards',requestId:first.id,policy:{maxRounds:3,stagnationLimit:2,minImprovement:.1}});
 refusal('unassessed-object',()=>cycle.propose('guards',first.id,[{objectId:3,field:'kind.runs.0.text',value:'forbidden'}],'unassessed'),/revision_not_assessed/);
 refusal('outside-authority',()=>cycle.propose('guards',first.id,[{objectId:99,field,value}],'outside'),/revision_outside_authorization/);
 refusal('duplicate-field',()=>cycle.propose('guards',first.id,[...changes,...changes],'duplicate'),/invalid_revision_targets/);
 refusal('legacy-bypass',()=>store.revision(first.id,changes),/revision_cycle_required/);
 const proposal=cycle.propose('guards',first.id,changes,'green');assert.deepEqual(proposal.authorization,{...authorization,objects:[2],fields:[field]});
 assert.deepEqual(cycle.propose('guards',first.id,changes,'green'),proposal);assert.equal(cycle.get('guards').rounds,1);records.push({case:'idempotent-proposal',result:'PASS',proposalId:proposal.id,rounds:1,sharedBudget:proposal.authorization.budgetId});
 refusal('overlapping-round',()=>cycle.propose('guards',first.id,changes,'overlap'),/revision_round_pending/);
 const plan=join(c.output,'plan.json');writeFileSync(plan,JSON.stringify({expectedProjectSha256:sourceManifest.files['project.vectorcraft'],operations:[{command:'paint.setFill',params:{ids:[2],color:'#00ff00'}}],exports:[{format:'svg',artboard:0},{format:'pdf',artboard:0},{format:'png',artboard:0}]}));
 const options={skill:join(c.installed,'skills/vectorcraft-use'),expectedSkillSha256:lock.sha256['vectorcraft-use'],plan,output:join(c.output,'revised'),runtimeHome:c.runtime,python:'/opt/anaconda3/bin/python3',estimatedBytes:4000000};
 for(const [name,path] of [['target',brief],['rubric',rubric]]){const before=readFileSync(path);writeFileSync(path,'explicit QA changed '+name);await refusedExecution('stale-'+name,proposal,options,/stale_review_binding/);writeFileSync(path,before);}
 await refusedExecution('wrong-source',proposal,{...options,source:c.output},/revision_source_mismatch/);
 const fakeSkill=join(c.output,'wrong-runtime');mkdirSync(join(fakeSkill,'scripts'),{recursive:true});writeFileSync(join(fakeSkill,'scripts/runtime.lock.json'),JSON.stringify({artifacts:{'darwin-arm64':{binarySha256:'0'.repeat(64)}}}));await refusedExecution('wrong-runtime',proposal,{...options,skill:fakeSkill},/revision_runtime_mismatch/);
 const execution=await cycle.execute('guards',proposal.id,options);assert.equal(execution.state,'awaiting_review');assert.equal(cycle.get('guards').latest,first.id);refusal('await-explicit-feedback',()=>cycle.propose('guards',first.id,changes,'automatic-next'),/revision_round_pending/);
 const wrongDirectory=join(c.output,'wrong-directory');cpSync(execution.output,wrongDirectory,{recursive:true});const wrong=await check(wrongDirectory);assert.equal(wrong.input.technicalStatus,'PASS');store.importReceipt(receipt(wrong,{structure:4,text:4,brand:4,layout:4,legibility:4},'QA wrong output must not become best'));
 refusal('wrong-output-lineage',()=>cycle.observe('guards',wrong.id,proposal.id),/revision_lineage_mismatch/);assert.equal(cycle.best('guards').requestId,first.id);
 const next=await check(execution.output);refusal('pending-review-is-not-feedback',()=>cycle.observe('guards',next.id,proposal.id),/checked_review_required/);
 const scores={structure:1,text:2,brand:3,layout:4,legibility:2.5};const response=receipt(next,scores,'QA latest issues for explicit second round');store.importReceipt(response);cycle.observe('guards',next.id,proposal.id);
 const best=cycle.best('guards');assert.equal(best.requestId,next.id);assert.equal(best.score,2.5);assert.deepEqual(best.unresolvedIssues,response.issues);assert.equal(best.sharedBudget.attempts,6);assert.equal(cycle.get('guards').rounds,1);
 const nextProposal=cycle.propose('guards',next.id,changes,'explicit-second-round');assert.equal(nextProposal.round,2);assert.equal(attempts(),6);assert.equal(cycle.ledger.db.prepare("SELECT COUNT(*) AS n FROM tasks WHERE key LIKE 'revision:%'").get().n,1);
 for(const [name,digest]of Object.entries(best.fingerprints)){const p=join(best.path,name);assert.equal(lstatSync(p).mode&0o222,0);assert.equal(hash(readFileSync(p)),digest);}
 writeFileSync(join(c.source,'project.vectorcraft'),'QA changed original source');writeFileSync(join(execution.output,'project.vectorcraft'),'QA changed reviewed candidate source');assert.deepEqual(cycle.best('guards'),{...best,rounds:2});
 const dep=join(best.path,'inputs/0'),bytes=readFileSync(dep);chmodSync(dep,0o600);writeFileSync(dep,'QA tampered retained target');refusal('best-dependency-tamper',()=>cycle.best('guards'),/best_candidate_changed/);writeFileSync(dep,bytes);chmodSync(dep,0o400);
 const project=join(best.path,'project.vectorcraft');chmodSync(project,0o600);writeFileSync(project,'QA tampered retained native');refusal('best-native-tamper',()=>cycle.best('guards'),/best_candidate_changed/);
 assert.equal(skillDigest(originalSource),originalDigest);const groups=cycle.ledger.db.prepare('SELECT task,epoch FROM native_processes').all() as any[];const {ProcessRegistry}=await load('src/harness/process_registry.ts');const registry=new ProcessRegistry(store.db);assert(groups.every(g=>registry.observe(g.task,g.epoch).stopped));
 const proof={schema:'vectorcraft-revision-guards-native/v1',result:'PASS',driverSha256:hash(readFileSync(process.argv[1])),pluginVersion:JSON.parse(readFileSync(join(c.installed,'plugin.json'),'utf8')).version,sourceRef:lock.ref,level:c.level,platform:process.platform+'-'+process.arch,records,initialRequest:first,proposal,execution,wrongDirectoryRequest:wrong,nextRequest:next,nextReceipt:response,nextProposal,best,sharedAttempts:attempts(),originalSourcePreserved:true,allGroupsStopped:true,registeredGroups:groups.length,scope:'real native execution and checked candidate lineage, explicit QA scores only; not complete6.6 qualification'};
 let text=JSON.stringify(proof,null,2)+'\n';for(const[from,to]of[[c.source,'QA_SOURCE'],[c.output,'QA_ROOT'],[originalSource,'ORIGINAL_SOURCE'],[c.installed,'INSTALLED_PLUGIN'],[c.runtime,'QA_RUNTIME']])text=text.split(from).join(to);writeFileSync(join(c.output,'proof.json'),text);console.log(JSON.stringify({result:'PASS',boundaryCases:records.length,sharedAttempts:attempts()}));
}finally{cycle.close();store.close();}
